from app.llms.llms import *
from app.schemas.schemas import *

from app.prompts.prompts import RELEVANCE_SYSTEM_PROMPT
from app.llms.llms import llm_groq
from app.api.fetch_news import fetch_news

from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv
from pprint import pprint

load_dotenv()

def build_article_context(news: NewsArticleCollection) -> str:
    """
    1) Build a string representation of the news articles to be used as context for the LLM.
    2) The context will include the article_id, headline, summary and source of each news article.
    3) The context will be used to generate relevance assessments for each news article with respect to the user's news request.
    """

    res = []
    for article in news.articles:

        res.append("Article ID:")
        res.append(article.article_id)

        res.append("Headline:")
        res.append(article.headline)

        res.append("Summary:")
        res.append(article.summary)

        res.append("Source:")
        res.append(article.source)

        res.append("*"*50)

    return "\n".join(res)


def generate_relevance_scores(request: NewsRequest, news: NewsArticleCollection) -> RelevanceAssessmentCollection:
    """
    1) Generate relevance scores for each news article with respect to the user's news request.
    2) The relevance scores [0.0-10.0] will be generated by the LLM using the context built from the news articles and the user's news request.
    3) This score will be used to filter the news articles and retain only those that are relevant to the user's news request.
    """
    
    context = build_article_context(news)
    topic = request.topic
    duration = request.duration

    prompt = ChatPromptTemplate.from_messages(
        [
            ('system', RELEVANCE_SYSTEM_PROMPT),
            ('human',"""

                User Request
                
                Topic:
                {topic}

                Duration:
                {duration}

                Articles:
                {articles}

                """
            )
        ]
    )

    structured_llm_groq = llm_groq.with_structured_output(RelevanceAssessmentCollection)

    chain = prompt | structured_llm_groq
    response = chain.invoke({
        "topic": topic,
        "duration": duration,
        "articles": context,
    })

    return response

if __name__== "__main__":

    request = NewsRequest(
        topic="Artificial Intelligence",
        duration="latest",
        format="short"
    )

    news = fetch_news(request)

    pprint(type(news))
    pprint(news)

    print("*"*100)

    assessment = filter_news(request, news)
    pprint(assessment.model_dump_json(indent=4))