from app.llms.llms import *
from app.schemas.schemas import *
from app.prompts.prompts import VERIFICATION_SYSTEM_PROMPT
from app.llms.llms import llm_groq

from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv
load_dotenv()

def build_verification_context(news: NewsArticleCollection) -> str:
    """
    1) Build a string representation of the news articles to be used as context for the LLM.
    2) The context will include the article_id, headline, summary and source of each news article.
    3) The context will be used to generate verification assessments for each news article with respect to the user's news request.
    """

    res = []
    for article in news.articles:

        res.append("Article ID:")
        res.append(article.article_id)

        res.append("Headline:")
        res.append(article.headline)

        res.append("Summary:")
        res.append(article.summary)

        res.append("Source:")
        res.append(article.source)

        res.append("*"*50)

    return "\n".join(res)


def generate_verification_scores(news: NewsArticleCollection) -> VerificationAssessmentCollection:
    """
    1) Generate verification scores for each news article with respect to the user's news request.
    2) The verification scores [0.0-10.0] will be generated by the LLM using the context built from the news articles and the user's news request.
    3) This score will be used to filter the news articles and retain only those that are verified to be trustworthy.
    """
    
    context = build_verification_context(news)
    prompt = ChatPromptTemplate.from_messages(
        [
            ('system', VERIFICATION_SYSTEM_PROMPT),
            ('human',"""
                Articles:
                {articles}
                """
            )
        ]
    )

    structured_llm_groq = llm_groq.with_structured_output(VerificationAssessmentCollection)

    chain = prompt | structured_llm_groq
    response = chain.invoke({
        "articles": context
    })

    return response

