from typing import Literal, List
from pydantic import BaseModel, Field, HttpUrl
from datetime import datetime


class NewsRequest(BaseModel):
    """
    Structured representation of the user's news request.
    """

    topic: str = Field(..., description = "The topic or domain the user wants news about. Example: AI, Cricket, Politics, Education.")
    duration: Literal["latest", "today", "last_week", "last_month", "over_the_years"] = Field(default = "latest", description = "Time period over which news should be fetched.")
    format: Literal["short", "medium", "long"] = Field(..., description = "Desired length of the final news summary.")


class NewsArticle(BaseModel):
    """
    Represents a single news article fetched from a news source.
    This is the output contract of the News Fetch Agent.
    """

    article_id: str = Field(..., description="Unique identifier of the news article returned by the news provider.")
    headline: str = Field(..., description="Short descriptive headline of the news article.")
    summary: str = Field(..., description="Brief summary or description of the news article extracted from the news provider.")
    source: str = Field(..., description="Platform or publisher from which the news was fetched. Example: Reuters, BBC, CNBC.")
    author: List[str] | None = Field(default=None, description="List of authors or publishers of the news article.")
    url: HttpUrl = Field(..., description="Direct URL pointing to the original news article or post.")
    published_at: datetime = Field(..., description="Date and time when the news article was originally published.")
    raw_text: str = Field(..., description="Original unmodified text exactly as fetched from the news provider.")


class NewsArticleCollection(BaseModel):
    """
    Represents a collection of news articles returned by the
    News Fetch Agent.
    """

    articles: List[NewsArticle] = Field(..., description="List of fetched news articles.")


class RelevanceAssessment(BaseModel):
    """
    Represents the semantic relevance assessment of a news article
    with respect to the user's news request.
    """

    article_id: str = Field(
        description="Unique identifier of the news article being evaluated. This should match the article_id in the corresponding NewsArticle object."
    )

    relevance_score: float = Field(
        ge=0.0,
        le=10.0,
        description=(
            "Semantic relevance score assigned by the LLM indicating how well the article satisfies the user's news request. "
            "0.0 - 2.0 = Completely Irrelevant. "
            "3.0 - 5.0 = Marginally Relevant. "
            "6.0 - 8.0 = Relevant. "
            "9.0 - 10.0 = Highly Relevant."
        )
    )

    keep: bool = Field(
        description=(
            "Indicates whether the article should be retained after semantic relevance evaluation. "
            "Only articles with keep=True will proceed to downstream stages like deduplication, verification, ranking and formatting."
        )
    )

    reason: str = Field(
        description=(
            "Provide a concise explanation (maximum 1-2 sentences) describing why the article was considered relevant or irrelevant with respect to the user's news request."
        )
    )


class RelevanceAssessmentCollection(BaseModel):
    """
    Represents the collection of relevance assessments generated by the
    Relevance Filter Agent.
    """

    assessments: List[RelevanceAssessment] = Field(..., description="Collection of relevance assessments generated for all fetched news articles.")

class DuplicateGroup(BaseModel):
    article_ids: list[str] = Field(..., description="Duplicate article_ids identified among the news articles.")
   
class DuplicateGroups(BaseModel):
    groups: list[DuplicateGroup] = Field(..., description="Collection of duplicate article_ids identified among the news articles in the form of a list.")